services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/seed/:/docker-entrypoint-initdb.d
      - ./postgresql/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
